### ISSUE TITLE
Cadastro Assistido --> ajustes no cadastro da Moradia

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#10]
Campo 'Nessa moradia desde' retirar, não é necessário
Campo 'Material de Construção' excluir a opção adobe

**Comment by hebertom** [comment]
Feito!

**Comment by monicacsvaz** [comment]
Campo 'Material de Construção' foi excluido - OK
Campo 'Nessa moradia desde' foi retirado, mas ao salvar o registro retorna o erro em anexo
![issue10_testes23042016](https://cloud.githubusercontent.com/assets/17314890/14763362/fb7d7dea-0969-11e6-8d7d-c78263c3710a.png)

**Comment by nunomazer** [comment]
Alterei no banco de dados o campo para aceitar nulos, Mônica pode testar novamente

**Comment by monicacsvaz** [comment]
OK, testado com sucesso
