### ISSUE TITLE
Cadastro de Documentos --> Validação de CPF

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#11]

**Comment by marciogurka** [comment]
@monicacsvaz aonde que aparece essa opção de cadastro de documentos? Não consegui localizar aqui. Obrigado

**Comment by monicacsvaz** [comment]
Para incluir Documento seguir os passos:
Cadastro --> Listar Pessoa --> seleciona uma pessoa que não tenha documentos (Monica C Vaz) --> Adicionar Novo --> Documentos

Para alterar Documento seguir os passos:
Cadastro --> Listar Pessoa --> seleciona uma pessoa --> Documentos --> Editar

**Comment by monicacsvaz** [comment]
Marcio, a issue #23 é para deixar o cadastro de documentos já na tela do cadastro de pessoa e está com o Heberton. Vou passar essa issue para ele pois acredito que faz mais sentido ok?

**Comment by marciogurka** [comment]
Ok

**Comment by hebertom** [comment]
Feito!

**Comment by monicacsvaz** [comment]
Heberton, a validação está ok, mas a mensagem de erro quando entra com um CPF incorreto está parte em ingles. Retornando para correção.

**Comment by hebertom** [comment]
Corrigido!

**Comment by monicacsvaz** [comment]
Teste realizado com sucesso
