### ISSUE TITLE
Menu Cadastro --> Adicionar nova pessoa - campo Data de Nascimento está vindo com a data atual.

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#12]
Deixar esse campo em branco como padrão

**Comment by nunomazer** [comment]
Marquei como alta prioridade pq é muito simples de mexer

**Comment by jgckruger** [comment]
Pelo que entendi do problema quando me foi explicado (data de aniversário = data de cadastro) o trecho de código que corresponde a parte que daria esse erro foi comentado. Eu não vi nada de errado no trecho, mas fica o commit abaixo para verificar isso.

Se o problema for só ficar com o formulário em braco aí é outra história para vermos.

Commit: 93ca816fca3b5ee859fa3c744b00165fd10fdd86

**Comment by nunomazer** [comment]
João, e demais,  não é possível começar a mexer no código antes do ambiente de desenvolvimento estar montado, senão faremos achismos

**Comment by monicacsvaz** [comment]
Ok, testado com sucesso.
![image](https://cloud.githubusercontent.com/assets/17314890/14763401/3a6e70d0-096b-11e6-8756-756a77cb17c4.png)
