### ISSUE TITLE
Cadastro --> Listar pessoas: mostrar na tela se é Assistido, Voluntário ou Funcionario

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#13]
Para facilitar as operações que podem ser feitas com a pessoa, o usuário pediu que seja mostrada em uma coluna na tela em anexo se é a pessoa é  Assistido, Voluntário ou Funcionario
![issue 13- listar pessoas - mostrar tipo](https://cloud.githubusercontent.com/assets/17314890/13254768/a8d7bc76-da21-11e5-9698-ef3ed47d0255.jpg)

**Comment by nunomazer** [comment]
Reforçando, uma pessoa pode ser uma dessas "categorias", ou mais de uma, pode ser um VOluntário e Funcionário, pode ser um Assistido e Funcionário, etc.

Talvez seja interessante adicionar como uma melhoria de mais alta prioridade, pois é simples e permitirá que o responsável por ela estude um pouco mais do sistema.

**Comment by monicacsvaz** [comment]
Ok, testado com sucesso
![image](https://cloud.githubusercontent.com/assets/17314890/14763394/abe3057e-096a-11e6-80f9-722c4501adc6.png)
