### ISSUE TITLE
Menu Atendimento --> Listar assistências: inserir paginação na tela de consulta

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#17]
Eu me refiro à tela de consulta acessada no menu Atendimento --> Listar Assistências. Avaliar se nessa precisa de paginação.

**Comment by nunomazer** [comment]
Já existe paginação para assistidos

**Comment by nunomazer** [comment]
Verificar e replanejar caso precise implementar

**Comment by nunomazer** [comment]
Sim precisa de paginação, pode distribuir esta tarefa para um dos programadores Mônica, mas vou replanejar para próxima Milestone ok!?

**Comment by monicacsvaz** [comment]
Marcio estou passando esse issue para vc pois não está com nenhum do primeiro milestone 'Pequenas Melhorias'. esse issue ficará para o próximo milestone mas vc pode começar a pesquisar como corrigir este. Obrigada

**Comment by marciogurka** [comment]
@nunomazer eu usei como base a paginação presente na tela "Cadastro -> Listar Pessoas", onde a paginação é inicializada com o seguinte trecho de código:

```
if ($this->persons instanceof Zend_Paginator) {
            echo $this->paginationControl(
                    $this->persons, 'Sliding', array('/paginator/search.phtml', 'aganacore'), array('filter_keyword' => $this->filter_keyword)
            );
        }
```

Ao utilizar na tela de assistências, ele diz que a variável `$this->activities`, que equivale no código à variável `$this->persons`, não é do tipo Zend_Paginator, e sim um vetor, como posso criar uma variável do tipo Zend_Paginator para utilizar na paginação?

**Comment by nunomazer** [comment]
Dá uma olhada no controlador de pessoa, se não me engano tem de mexer na ação e definir um carregamento diferente do modelo, que nesse caso será a carga de atividades

**Comment by marciogurka** [comment]
Criei um controlador novo baseado nesse de pessoa, como eu faço pra colocar esse controlador na view correta? Não sei se é algum tipo de arquivo de rota ou algo assim

**Comment by nunomazer** [comment]
Você só tem que chamar o URL correto para que o dispatch do Zend instancie o controllador específico e execute a ação correta .. verifique na documentação do Zend como funcionam os segmentos de url para executar o MVC

**Comment by marciogurka** [comment]
@nunomazer eu consegui criar um controller baseado no arquivo "PersonsController.php", que é um controller de uma view que possui paginação. Consegui criar a view e fazer o dispatch instanciar o controller e ação correta, porém ainda não aparece a paginação, nesse trecho aqui:

`if ($this->activities instanceof Zend_Paginator) {
            echo $this->paginationControl(
                    $this->activities, 'Sliding', array('/paginator/search.phtml', 'aganacore'), array('filter_keyword' => $this->filter_keyword)
            );
        }`

do arquivo `/agana/agana/modules/assistance/views/scripts/activities/list.phtml` que eu dei push nessa última alteração, o controller se encontra no arquivo `/agana/agana/modules/assistance/controllers/ActivitiesController.php`.

Ele coloca uma variável $paginator pelo trecho

`$paginator = ($this->_hasParam('paginator')) ? filter_var($this->_getParam('paginator'), FILTER_VALIDATE_BOOLEAN) : true;`

porém não sei como realizar as alterações para aparacer a paginação.

**Comment by nunomazer** [comment]
Hummm, parece que tá tudo certo, sugestões e questões:

1 - A listagem mostra somente uma página de assistências? Ou continua mostrando todas?

2 - Se mostra somente uma página então a query já está paginando no controlador, o problema é somente mostrar o componente de navegação certo!? Faz um teste e tenta imprimir a classe do objeto assim `get_class($this->activities)`

3 - Se mostra todos então tem que confirmar o problema no controlador e se realmente está passando pela action correta, o que me parece que está

**Comment by marciogurka** [comment]
@nunomazer a listagem deveria aparentar como na página 'Cadastros -> Listar Pessoas', ou seja, se tiver pelo menos um registro, a paginação aparece. Porém nem isso está aparecendo. A query está sendo mostrada corretamente, ou seja, as assistências são mostradas, porém não aparece os controles de navegação da paginação.

Tentando imprimir do jeito que você mostrou ali, aparece:

 `get_class() expects parameter 1 to be object, array given in \ongonline\agana\agana\modules\assistance\views\scripts\activities\list.phtml on line 164`

Aí tentei imprimir dentro desse loop:
`
foreach ($this->activities as $act) {
          echo get_class($act);
`

e o resultado foi:
Assistance_Model_Activity

Aparentemente ele está buscando todos os registros de forma correta, porém não está inicializando certo apenas os controles da navegação.

**Comment by nunomazer** [comment]
@marciogurka essa mensagem já indica o problema: `get_class() expects parameter 1 to be object, array given`... por algum motivo está sendo carregado um array e não o objeto no `activities`.

Tenta dar um var_dump no activities logo na linha seguinte qwue ele é criado na ação do controlador, dá um die para poder parar ali mesmo a execução e ver o que ele mostra.

**Comment by marciogurka** [comment]
@nunomazer O resultado é:
`array(1) { [0]=> object(Assistance_Model_Activity)#208 (17) { ["id":"Assistance_Model_Activity":private]=> string(1) "1" ["assistance_date":"Assistance_Model_Activity":private]=> string(10) "2015-01-06" ["assistance_time":"Assistance_Model_Activity":private]=> string(8) "23:00:00" ["person_helped_id":"Assistance_Model_Activity":private]=> string(1) "1" ["person_performed_id":"Assistance_Model_Activity":private]=> string(1) "1" ["person_recorded_id":"Assistance_Model_Activity":private]=> string(1) "1" ["description":"Assistance_Model_Activity":private]=> string(10) "dadasdasda" ["appaccount_id":"Assistance_Model_Activity":private]=> string(1) "1" ["task_type_id":"Assistance_Model_Activity":private]=> string(1) "2" ["project_id":"Assistance_Model_Activity":private]=> string(0) "" ["event_id":"Assistance_Model_Activity":private]=> string(0) "" ["id_by_finger_key":"Assistance_Model_Activity":private]=> string(0) "" ["person_helped":"Assistance_Model_Activity":private]=> NULL ["person_performed":"Assistance_Model_Activity":private]=> NULL ["person_recorded":"Assistance_Model_Activity":private]=> NULL ["task_type":"Assistance_Model_Activity":private]=> NULL ["project":"Assistance_Model_Activity":private]=> NULL } }`

Procurando e comparando com a tela de listar pessoas (que possui uma paginação já), verifiquei que os métodos _getAll_ são diferentes.

Arquivo `Persons_Domain_Person`:

`/**
     * Returns all the persons persisted in database for a tenant based on 
     * appaccount_id
     * 
     * @param int $appaccount_id
     * @param String $orderby
     * @param boolean $paginator
     * @param array $params
     * @return array<Persons_Model_Person>
     * @throws Exception
     */
    public function getAll($appaccount_id, $orderby = 'name', $paginator = true, $params = array()) {
        try {
            $u = new Persons_Persist_Dao_Person();
            $r = $u->getAll($appaccount_id, $orderby, $paginator, $params);
            $r = is_null($r) ? array() : $r;
            return $r;
        } catch (Exception $e) {
            throw $e;
        }
    }`

Arquivo `Assistance_Domain_Activity`

`public function getAll($orderby = 'assistance_date, assistance_time') {
        try {
            $u = new Assistance_Persist_Dao_Activity();
            $r = $u->getAll(array(
                'appaccount_id' => Zend_Auth::getInstance()->getIdentity()->appaccount_id,
                'orderby'       => $orderby
            ));
            return is_null($r) ? array() : $r;
        } catch (Exception $e) {
            throw $e;
        }
    }`

Está correto a observação? Se sim, é melhor criar um método novo ou alterar esse?

**Comment by nunomazer** [comment]
Correto, então precisa acertar este método no `Assistance_Domain_Activity` seguindo a mesma lógica do de persons, verifique se não tem também que mudar algo no Dao: `Assistance_Persist_Dao_Activity`, não lembro se as classes base de Dao estão com o getAll pronto para receber o parâmetro de paginação, se estiverem diferentes os getAll das classes Dao de Persons e Activity, adapte a lógica do Activity.

**Comment by marciogurka** [comment]
Ok, vou fazer isso, qualquer dificuldade eu mando aqui

**Comment by marciogurka** [comment]
![ongonline](https://cloud.githubusercontent.com/assets/16693227/16167729/ebfae64c-34ce-11e6-8f3e-f4635d32f11e.png)

No ambiente local a paginação apareceu de forma correta, pronto para teste no ambiente de desenvolvimento!

**Comment by monicacsvaz** [comment]
testado e está OK. 
![image](https://cloud.githubusercontent.com/assets/17314890/16248445/98ba56ec-37e5-11e6-9599-8139871dfb86.png)
