### ISSUE TITLE
Cadastro de Assistido - não deixar os campos abaixo obrigatórios

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#18]
1-Religiao
2-Ocupação somente ser obrigatório se usuário marcar OUTRO
3-Situação da moradia somente ser obrigatório se usuário marcar OUTRO
4-Situada em area da moradia somente ser obrigatório se usuário marcar OUTRO
5-Material de construção somente ser obrigatório se usuário marcar OUTRO
6-Peças da casa

**Comment by nunomazer** [comment]
Alterações rápidas de interface, verificar se precisa deixar os campos como aceitando NULL no banco de dados

**Comment by hebertom** [comment]
Os itens 1 e 6 foram feitos. Quanto ao 2, 3, 4 e 5 eu estou com algumas dúvidas. Acredito que para essa versão de testes não conseguirei solucionar.

**Comment by monicacsvaz** [comment]
Não consigo testar devido ao erro relatado no issue #10

**Comment by nunomazer** [comment]
Acho então que todos devem ser opcionais, sugestão. Já alterei os campos para aceitarem nulo pq senão não é possível que sejam opcionais.
Mônica pode testar e comprovar se isto já funciona ou ainda precisa de alguma alteração de código? Se precisar redistribua para o Hébertom por favor.

**Comment by monicacsvaz** [comment]
Ok, testado com sucesso
