### ISSUE TITLE
Acessos - criar novos usuários

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#20]
A Equipe está pedindo para criar usuários para Marcel, Lidiane e Ana Carolina.  Estão questionando que o sistema não deveria deixar o mesmo usuário logar em mais de uma maquina ao mesmo tempo
Dúvida: Eles tem como cadastrar usuários no sistema?

**Comment by nunomazer** [comment]
Vou dividir esta tarefa em três diferentes
