### ISSUE TITLE
Cadastro --> Listar pessoa: Verificar se pode fazer a consulta sem usar o caracter %

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#21]
Se puder, deixar sem o caracter.

**Comment by nunomazer** [comment]
É possível mas tem que deixar fixo no código pois o % é um coringa. O ideal então é na string de SQL montada com o parâmetro, deixar o seguinte:  

```
.... LIKE '%'. $parametro . '%' ...
```

Por favor, quem for alterar esta característica fique atento que o exemplo anterior foi feito de cabeça, não sei o nome da variável que está sendo utilizada

**Comment by hebertom** [comment]
Solução: 

No método getAll da classe ongonline/agana/agana/modules/persons/persist/dao/Person.php troquei:
`$sql->where('lower(unaccented(name)) LIKE ?', $filter->filter($params['filter-keyword']));`
por: 
`$sql->where('lower(unaccented(name)) LIKE ?', '%' . $filter->filter($params['filter-keyword']) . '%');`

**Comment by monicacsvaz** [comment]
Ok, testado com sucesso. Foi testado com tres caracteres MON e a pesquisa foi realizada com sucesso. 
![issue21_testes23042016](https://cloud.githubusercontent.com/assets/17314890/14763307/187db2b8-0968-11e6-907c-390875401f97.png)
