### ISSUE TITLE
Cadastro --> Adicionar noma pessoa: cadastro de documentos já no momento do cadastro da pessoa

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#23]
Hoje no sistema é cadastrada a pessoa e depois deve-se fazer uma pesquisa por esta pessoa para entrar na tela de cadastro de documento. Avaliar a possibilidade de já no cadastro da pessoa colocar um link para inserir os documentos.

**Comment by hebertom** [comment]
Feito! 

Mônica, favor testar somente após o Ademir realizar a tarefa #41 de alteração do banco de dados.

**Comment by nunomazer** [comment]
Mônica precisa testar esta tarefa para colocarmos em produção o quanto antes, isoladamente mesmo, pois o banco foi alterado

**Comment by monicacsvaz** [comment]
qual o endereço do ambiente de teste? eu entrei no mesmo da vez passada e não mostra os documentos para serem cadastrados no momento do cadastro da pessoa.. seria essa a alteração do #23 certo?
 Mônica Cristine Scherer Vaz
Doutoranda em Engenharia da Produção - Universidade Tecnológica do Paraná (UTFPR)Mestre em Computação Aplicada na Agricultura (UEPG)Contato (41) 9138-0743 

```
Em Segunda-feira, 2 de Maio de 2016 8:36, Ademir Mazer Jr [ Nuno ] <notifications@github.com> escreveu:
```

 Mônica precisa testar esta tarefa para colocarmos em produção o quanto antes, isoladamente mesmo, pois o banco foi alterado —

**Comment by nunomazer** [comment]
É o mesmo, acabei de fazer o deploy, mas já vi que faltou traduzir os campos na interface para o usuário

**Comment by monicacsvaz** [comment]
Ok o teste, mas falta traduzir os campos e mensagens de erro. Vou manter aberto para retestar após correção.

**Comment by hebertom** [comment]
Corrigido!

**Comment by monicacsvaz** [comment]
Teste realizado com sucesso
