### ISSUE TITLE
Verificar a gestão de usuários 

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#28]
Permitir aos usuários comuns do sistema a gestão de usuários da conta. Ref #20

**Comment by nunomazer** [comment]
Monica pode verificar se seu usuário consegue manipular os demais no sistema?
Seu usuário podendo criar grupos e atribuir permissões é o mesmo que outro "usuário comum" fazer esta gestão, bastaria apenas atribuir esta permissão a um deles para que possam cadastrar e alterar usuários quando necessário.

**Comment by monicacsvaz** [comment]
Meu usuário consegue alterar o perfil dos usuários do sistema. Dessa forma ficarei com essa demanda e podemos definir um usuário no futuro, do Ministerio, para assumir essa demanda.
