### ISSUE TITLE
Destinar as tarefas aos responsáveis

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#29]
@monicacsvaz é preciso distribuir as tarefas do milestone Pequenas Melhorias, você pode fazer isso?
Para ver as tarefas por milestone basta filtrar como na tela abaixo

![vagrant nti-uepg -vagrant-workspaces-proplan-smartboard-server_001](https://cloud.githubusercontent.com/assets/652935/13612728/bbcef868-e547-11e5-87bd-b2a79b999e4f.png)

**Comment by monicacsvaz** [comment]
Ok, dividido de acordo com os issues de um mesmo grupo de requisitos. Os que estavam para vc, deixei assim. Se for para redirecionar avisa. Obrigada

**Comment by nunomazer** [comment]
Os que estão comigo pode deixar
