### ISSUE TITLE
Menu ATENDIMENTO - Na combo Tipo de Tarefa mostra a tarefa pai e as filhas. Verificar se não deveria aparecer somente as filhas, pois a pai é um grupo e as filhas um subgrupo

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#3]
![issue 3 - lista de tarefas no cadastro de atendimento](https://cloud.githubusercontent.com/assets/17314890/13249880/7c7af7ae-da05-11e5-9b83-47849eb3013c.jpg)

**Comment by nunomazer** [comment]
A princípio o grupo poderia ser escolhido, se mostrar somente as filhas muda a regra porém cria um padrão que pode ser utilizado.

**Comment by nunomazer** [comment]
Deve ser implementado como alta prioridade para evitar entao lançamentos no grupo desde o início, assim não cria-se um problema para os primeiros relatórios

**Comment by monicacsvaz** [comment]
Testado e continua com o mesmo problema. favor verificar
![image](https://cloud.githubusercontent.com/assets/17314890/14960957/bbbc881c-106d-11e6-8813-ced0439ad1de.png)

**Comment by marciogurka** [comment]
Favor testar novamente para verificar se o problema foi resolvido na tela de Evento também

**Comment by monicacsvaz** [comment]
Márcio, na tela está mostrando somente as tarefas PAI... é para mostrar as FILHAS..... veja o enunciado.

Nas duas telas: 1) Lançar atendimento individual   e   2) Novo evento, o que deve ser mostrado na combo TAREFA são as tarefas filhas. 
Eu havia te passado o seguinte: "Marcio, na correção que foi feita, foi somente na tela ' Lançar atendimento individual ' e está aparecendo somente a pai. Tem que mostrar as filhas"

E agora que vc corrigiu está somente as tarefas PAI.... não estou entendendo onde não está claro a correção que deve ser feita.

![image](https://cloud.githubusercontent.com/assets/17314890/15114321/ccfd2e26-15cf-11e6-812c-0c7a034ceb72.png)

**Comment by nunomazer** [comment]
@marciogurka é necessário fazer alterações contextuais no código com preocupação em relação a toda a estrutura e como elas podem afetar outras partes. 

Você alterou uma função chamada `getAllParentTasks`, que tem por objetivo **retornar todas as tarefas pai**, e mudou o comportamento dela para retornar todas as tarefas que não são pai.

Isto significa que onde esta função for chamada para retornar as tarefas pai, retornará dados errados.

Por favor, crie uma função específica para retornar todas as tarefas que não são pai (que tem filhos) e altere a chamada no ponto onde ela precisa ser executada.

**Comment by marciogurka** [comment]
@nunomazer Eu criei esse método na primeira vez que realizei a tarefa, só é chamada nesses lugares, já renomeei o método para evitar confusões futuras.

**Comment by monicacsvaz** [comment]
Teste realizado com sucesso.
![image](https://cloud.githubusercontent.com/assets/17314890/15344247/d32b90e6-1c7b-11e6-9632-64a10cce5b8d.png)
