### ISSUE TITLE
Erro ao acessar a view principal do projeto

### ISSUE THREAD

**Issue by hebertom** [nunomazer/ongonline#30]
Ao acessar a view principal do projeto dentro de ongonline/app retorna o seguinte erro: App error log file or directory is not writable

**Comment by hebertom** [comment]
Resolvido!

**Comment by nunomazer** [comment]
Descreve a solução para ajudar quem possa vir a tê-la no futuro

**Comment by hebertom** [comment]
Adicionar a pasta (descompactada) em anexo no diretório "ongonline/agana"
[data.zip](https://github.com/nunomazer/ongonline/files/198116/data.zip)
