### ISSUE TITLE
Criar cópia/modelo do banco de dados

### ISSUE THREAD

**Issue by marciogurka** [nunomazer/ongonline#31]
Tentei usar o modelo de desenvolvimento, porém não tenho o modelo do banco, qual o procedimento pra usar o sistema e conseguir testar o mesmo???

![screenshot_1](https://cloud.githubusercontent.com/assets/16693227/14061225/ba5a26e0-f359-11e5-8c4e-800746c0c741.png)

**Comment by nunomazer** [comment]
Vou gerar um dump da base de dados e passo para vocês

**Comment by nunomazer** [comment]
Criado um dump da estrutura no diretório docs
