### ISSUE TITLE
erro ZEND maquina do Bruno

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#33]
Em meu NetBeans o ZEND está dando erro
Não consigo adicionar o framework no netbeans, mesmo vendo diversos tutoriais na internet

Irei instalar em uma maquina virtual e ver se consigo fazer rodar

Infelizmente ainda não alterei nada no GitHub, mas essa semana ja darei uma posição!
Eu instalei o XAMPP e baixei o script .BAT em Opções do NetBeans, mas não sei pq aparece esse erro! 
![erro zend](https://cloud.githubusercontent.com/assets/17314890/14183465/e0d3a468-f746-11e5-9b43-1c0d6d91f246.jpg)

**Comment by nunomazer** [comment]
Veja a issue #37 Bruno
