### ISSUE TITLE
Netbeans não abre o projeto como se fosse do Zend - .zfproject.xml

### ISSUE THREAD

**Issue by jgckruger** [nunomazer/ongonline#36]
O netbeans não está reconhecendo o projeto como se fosse um projeto zend, e sim como um projeto em PHP puro.
Acredito que um dos problemas seja a falta do arquivo .zfproject.xml
Outro problema é quando apertado o botão para rodar o projeto ele não abre. Acho que o problema é só quanto a URL do projeto, que eu não tenho.

![url](https://cloud.githubusercontent.com/assets/14897794/14225003/623a94ce-f889-11e5-8e8e-5bd694798338.png)

**Comment by nunomazer** [comment]
Isso não é um problema pois o projeto em Php pode ser desenvolvido em qq ide, inclusive bloco de notas. Não deve ser um impedimento. 
A configuração do ide é particular de cada desenvolvedor.

Você não precisa executar pelo ide, até pq existe uma arquitetura diferente de um projeto direto em Php.  Abra o navegador e digite o endereço do projeto servido pelo web server (apache ou nginx)...  Provavelmente localhost/caminhodoprojeto/app
