### ISSUE TITLE
Projeto Zend no Netbeans

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#37]
Caros,

não se apeguem à necessidade/facilidade de criação de um projeto do tipo zend no Netbeans.

Zend framework é escrito em PHP, e pode ser programado até no Bloco de Notas como qualquer software em PHP, portanto, passem para frente, criem um projeto PHP normal e comecem a trabalhar no código.

Inclusive, se este projeto utilizasse da facilitação do zendproject.xml ele estaria presente, porém não é o caso. Sugiro a vocês ignorarem qualquer tópico de tutorial que descreva seu uso.

**Comment by nunomazer** [comment]
PS: respondam com um OK para eu fechar a issue assim que todos lerem

**Comment by HelioMarques** [comment]
Ok.

2016-04-05 13:08 GMT-03:00 Ademir Mazer Jr [ Nuno ] <
notifications@github.com>:

**Comment by hebertom** [comment]
Ok.

**Comment by nunomazer** [comment]
Estou fechando esta issue, ela ficará referenciada na wiki do projeto
