### ISSUE TITLE
Deploy milestone Pequenas Melhorias

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#39]
Deploy da milestone

**Comment by nunomazer** [comment]
Publicado Mônica, pode verificar se está ok? Se sim basta fechar esta issue

**Comment by monicacsvaz** [comment]
Versão validada com sucesso para entrega ao Ministerio no dia 25-04-2016.
Issues que foram corrigidos nessa versão:
![image](https://cloud.githubusercontent.com/assets/17314890/14790232/be3b8b06-0ae6-11e6-871b-c4ef60dfc949.png)
