### ISSUE TITLE
Como definir o deploy de testes?

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#42]
Mônica, o que acha de você criar uma nova issue destinada a mim sempre que for testar um grupo de alterações? Eu vi que o Hebertom colocou algumas como pendentes de teste desde p último deploy, porém não acho produtivo ficar colocando elas no ar a cada ussei destinada a testes.

Minha sugestão é, você cria a issue com o assunto Deploy de testes, destina a mim, tão logo eu o faça fecho a issue, assim você fica sabendo que pode está pronto para testar.  Talvez para orientar melhor seus testes, você possa colocar no corpo da issue a relação que irá testar.

**Comment by monicacsvaz** [comment]
Oi ademir..pode ser sim...eu vi que ele passou para e te mas eu rstou esperando os outros corrigirem os issues do Milestone abril/2016 para testar todos juntos....qdo eu for teste eu abro antes entao para vc... obrigda

Enviado do Yahoo Mail no Android

De:"Ademir Mazer Jr [ Nuno ]" notifications@github.com
Data:12:00 Ter, 3 de mai de PM
Assunto:[nunomazer/ongonline] Como definir o deploy de testes? (#42)

Mônica, o que acha de você criar uma nova issue destinada a mim sempre que for testar um grupo de alterações? Eu vi que o Hebertom colocou algumas como pendentes de teste desde p último deploy, porém não acho produtivo ficar colocando elas no ar a cada ussei destinada a testes.

Minha sugestão é, você cria a issue com o assunto Deploy de testes, destina a mim, tão logo eu o faça fecho a issue, assim você fica sabendo que pode está pronto para testar. Talvez para orientar melhor seus testes, você possa colocar no corpo da issue a relação que irá testar.

**Comment by nunomazer** [comment]
Combinado, assim fica mais organizado o workflow.  Acredito que podemos seguir a mesma regra para deploy e produção, depois que vc aprovar os testes e,se necessário, validar com o cliente, abre uma issue para deploy em produção
