### ISSUE TITLE
Canal de discussões no slack

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#43]
Pessoal, criei um canal para discussões no slack, por favor me mandem seus emails para que eu possa enviar o convite

**Comment by nunomazer** [comment]
Monica por favor me passe os emails de todos os integrantes para utiulizarmos o slack como canal de discussão

**Comment by monicacsvaz** [comment]
Segue:
...
monicacsvaz@yahoo.com.br

O João e o Helio não estão mais no projeto.
