### ISSUE TITLE
Deploy de testes - Entrega II

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#44]
Ademir, favor fazer o deploy para eu testar os issues:
#3, #8, #11, #16, #23.

Obrigada

**Comment by monicacsvaz** [comment]
Favor fazer novo deploy para retestar os issues #3 e #16

**Comment by nunomazer** [comment]
Monicam não vi nenhuma alteração de código no repositório relacionada à issue #16 ... e estou negando a issue #3 pq o Marcio fez uma alteração que vai quebrar o código em outras partes, fiz comentários na issue a respeito

**Comment by monicacsvaz** [comment]
Ademir, falei com o Bruno e com o Marcio e ambos falaram que esta ok... favor gerar novamente. Caso vc verifique que eles estão fazendo algo que não esteja de acordo, favor orienta-los novamente. Obrigada

**Comment by nunomazer** [comment]
Desculpem a demora, deploy de testes realizado
