### ISSUE TITLE
Favor excluir as pessoas listadas na figura 

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#45]
Foram feitos testes incluindo as pessoas abaixo. favor excluir do BD.

![image](https://cloud.githubusercontent.com/assets/17314890/15114656/53d4e460-15d1-11e6-9807-b50943147944.png)

**Comment by monicacsvaz** [comment]
Obs: Monica dos Santos Gonçalves não é para excluir.

**Comment by nunomazer** [comment]
Registros excluídos, mantive o de id 2027 pois é necessário ter uma pessoa cadastrada para ter usuário no sistema, excluí deste registro apenas as informações de funcionário e assistido
