### ISSUE TITLE
Deploy de testes - Entrega III

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#48]
Ademir, pode gerar uma versão de testes com o issue #4 para eu testar a interface que o Heberton fez? Os demais issues do Milestone Maio 2 / 2016   os meninos estão com dificuldade de corrigir.... gostaria de adiantar os testes, pois se tiver grandes alterações na tela dá tempo do Heberton trabalhar ainda para a mesma versão.

**Comment by nunomazer** [comment]
Deploy de testes realizado, com as alterações do Hebertom e Márcio
