### ISSUE TITLE
Menu CADASTRO --> ADICIONAR NOVA PESSOA - avaliar a opção de cadastrar uma nova região estando no cadastro de pessoa

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#5]
Segundo usuário, ao estar cadastrando uma pessoa, se a regiao não está na lista, ele vai perder o que estava digitando para sair e ir no cadastro de regiões.
A mesma solicitação foi feita para cadastro das cidades (AVALIAR)

![issue 5 - campo regiao para digitacao](https://cloud.githubusercontent.com/assets/17314890/13252145/a4061bba-da13-11e5-9fb6-be3eff730030.jpg)

**Comment by nunomazer** [comment]
É possvel e válido, porém tem de definir com o Melhr Viver qual o impacto de prioridade em relação à outras melhorias, pois o esforço para criar as rotinas que abrem janelas de cadastro sobre éoutras  relativmente alto.

**Comment by monicacsvaz** [comment]
estou mudando para a Milestone Maio/2016 para melhor avaliação

**Comment by monicacsvaz** [comment]
De acordo com a ultima reuniao com a Manu, vimos que esta necessidade não tem mais prioridade e vamos aguardar se no futuro precisará alteração.
