### ISSUE TITLE
Menu CADASTRO --> ADICIONAR NOVA PESSOA -campo website não é necessário

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#6]
![issue 6 - campo website](https://cloud.githubusercontent.com/assets/17314890/13252416/509dea64-da15-11e5-9822-47206fb387c0.jpg)

**Comment by nunomazer** [comment]
Não há problema de retirar, como é um campo que aceita nulos no banco de dados, dá para mexer somente na tela.

Alteraçao simples, vou marcar como prioridade alta pois pode ser resolvida rapidamente.

**Comment by jgckruger** [comment]
Mudei o trecho de código em que é chamada a função. Agora o campo deve estar como opcional(o que já deveria estar, porque da maneira que foi programado já era opcional).

Não consigo testar, mas a mudança não deve causar nenhum problema.

Commit: f158bc89d749ff33bac209828b0f9c1a4e570553

**Comment by monicacsvaz** [comment]
A solicitação era para retirar o campo da tela, ele já era opcional, e continua na tela. favor corrigir.

**Comment by hebertom** [comment]
Feito!

**Comment by monicacsvaz** [comment]
Testado com sucesso. 
![image](https://cloud.githubusercontent.com/assets/17314890/14959858/e62453ec-1067-11e6-821d-2b8dfc36f519.png)
