### ISSUE TITLE
Labels de prioridade

### ISSUE THREAD

**Issue by nunomazer** [nunomazer/ongonline#7]
Caros, criei 3 labels novos para que possamos, além de classificar as issues de acordo com a natureza (enhancement, bug,help, duplicated), ação (invalid, wont fix), determinar a prioridade: Priority High, Low e Medium.

Creio que esta ãpriorizaço deve ser realizada em conjunto com o Melhor Viver, que indicam o que está sendo mais impactante/urgente dentre as questões levantadas.

Também foi criado um label para apontar que entradas de issues são discussões de natureza diversa, como esta issue.

**Comment by monicacsvaz** [comment]
Ademir, vou marcar com a equipe do Melhor Viver para fechar se as prioridades estão de acordo como classifiquei. Eu segui o seguinte raciocínio:
- High: alterações necessárias para eles operacionalizarem o sistema num primeiro momento de acordo com as necessidades que eles descreveram
- Medium: alterações que vão facilitar a vida deles mas que podem esperar um segundo momento
- Low: aquelas correções de conteudo de lista e acessos, mas que eles podem ir trabalhando num primeiro momento.

**Comment by monicacsvaz** [comment]
Olá Ademir, você tem uma previsão de quando a equipe poderá começar a trabalhar nas alterações? Eu sugeri uma data de 21-03 para termos uma primeira avaliação de como está indo o desenvolvimento. Se esta data não for possível, podemos estipular uma para podermos acompanhar e passar ao Ministério? Aqueles issues que já estão classificados como High e que você já fez uma avaliação, eles poderiam iniciar?
