### ISSUE TITLE
Cadastro Pessoa --> tela de inserir e editar DOCUMENTOS: deixar o campo PIS/NIS/NIT nesse campo

### ISSUE THREAD

**Issue by monicacsvaz** [nunomazer/ongonline#8]

**Comment by nunomazer** [comment]
Para isso é necessário adicionar um campo na tabela de documentos e também nesta tela, ou ao gravar os documentos, adicionar um registro na tabela de documentos de número único (projetos federais).

Acredito que a primeira opção seja mais rápida

**Comment by hebertom** [comment]
Feito!

**Comment by monicacsvaz** [comment]
O campos PIS/NIS/NIT não está sendo mostrado para no momento da inclusão da pessoa. Como os documentos foram para esta tela de inclusão, este campo deve estar junto.

Na edição, o campo PIS está sendo mostrado no início da tela. Seria melhor se estivesse junto com os documentos, e deve-se chamar PIS/NIS/NIT e não somente PIS.

**Comment by hebertom** [comment]
Corrigido!

**Comment by monicacsvaz** [comment]
Teste realizado com sucesso.
